import { TransactionListFilters, TransactionStatusOptions, TransactionTypeOptions } from "./types";
import { TrendingDown, TrendingUp } from "lucide-react";


export const transactionListFilters: TransactionListFilters = {
    search: '',
    transactionType: '',
    transactionStatus: '',
    startDate: undefined,
    endDate: undefined,
}

export const transactionTypeOptions: TransactionTypeOptions[] = [
    {
        value: "credit",
        label: "Credit",
        light_color: "#f0fdf4",
        dark_color: "#22c55e",
        icon: TrendingUp,
    },
    {
        value: "debit",
        label: "Debit",
        light_color: "#fefce8",
        dark_color: "#eab308",
        icon: TrendingDown
    },
]

export const transactionStatusOptions: TransactionStatusOptions[] = [
    {
        value: "SUCCESS",
        label: "Success",
        light_color: "#f0fdf4",
        dark_color: "#22c55e",
        icon: TrendingUp,
    },
    {
        value: "PENDING",
        label: "Pending",
        light_color: "#fefce8",
        dark_color: "#eab308",
        icon: TrendingDown
    },
    {
        value: "FAILED",
        label: "Failed",
        light_color: "#FF0000/20",
        dark_color: "#FF0000",
        icon: TrendingDown
    },
]

export const transactionListData = [
    {
        transactionId: "TXN-2024-001",
        customerName: "Ankita",
        date: "17 AUG,2025",
        category: "Kitty",
        modeOfPayment: "Scanner",
        type: "credit",
        amount: 85000,
    },
    {
        transactionId: "TXN-2024-002",
        customerName: "Rahul",
        date: "15 JUL,2025",
        category: "Gold investors",
        modeOfPayment: "UPI",
        type: "debit",
        amount: 42000,
    },
    {
        transactionId: "TXN-2024-003",
        customerName: "Priya",
        date: "12 JUN,2025",
        category: "E-Commerce",
        modeOfPayment: "Bank Transfer",
        type: "credit",
        amount: 120000,
    },
    {
        transactionId: "TXN-2024-004",
        customerName: "Vikas",
        date: "10 MAY,2025",
        category: "Diamond",
        modeOfPayment: "UPI",
        type: "credit",
        amount: 95000,
    },
    {
        transactionId: "TXN-2024-005",
        customerName: "Sneha",
        date: "08 APR,2025",
        category: "Kitty",
        modeOfPayment: "Scanner",
        type: "debit",
        amount: 30000,
    },
    {
        transactionId: "TXN-2024-006",
        customerName: "Amit",
        date: "25 MAR,2025",
        category: "Gold investors",
        modeOfPayment: "Bank Transfer",
        type: "credit",
        amount: 67000,
    },
    {
        transactionId: "TXN-2024-007",
        customerName: "Neha",
        date: "18 FEB,2025",
        category: "E-Commerce",
        modeOfPayment: "UPI",
        type: "debit",
        amount: 54000,
    },
    {
        transactionId: "TXN-2024-008",
        customerName: "Rohit",
        date: "14 JAN,2025",
        category: "Diamond",
        modeOfPayment: "Scanner",
        type: "credit",
        amount: 110000,
    },
    {
        transactionId: "TXN-2024-009",
        customerName: "Kiran",
        date: "09 DEC,2024",
        category: "Kitty",
        modeOfPayment: "Bank Transfer",
        type: "debit",
        amount: 25000,
    },
    {
        transactionId: "TXN-2024-010",
        customerName: "Manish",
        date: "02 NOV,2024",
        category: "Gold investors",
        modeOfPayment: "UPI",
        type: "credit",
        amount: 80000,
    },
    {
        transactionId: "TXN-2024-011",
        customerName: "Divya",
        date: "28 OCT,2024",
        category: "E-Commerce",
        modeOfPayment: "Scanner",
        type: "debit",
        amount: 47000,
    },
    {
        transactionId: "TXN-2024-012",
        customerName: "Suresh",
        date: "21 SEP,2024",
        category: "Diamond",
        modeOfPayment: "Bank Transfer",
        type: "credit",
        amount: 105000,
    },
    {
        transactionId: "TXN-2024-013",
        customerName: "Pooja",
        date: "15 AUG,2024",
        category: "Kitty",
        modeOfPayment: "UPI",
        type: "credit",
        amount: 60000,
    },
    {
        transactionId: "TXN-2024-014",
        customerName: "Ravi",
        date: "10 JUL,2024",
        category: "Gold investors",
        modeOfPayment: "Scanner",
        type: "debit",
        amount: 39000,
    },
    {
        transactionId: "TXN-2024-015",
        customerName: "Meena",
        date: "05 JUN,2024",
        category: "E-Commerce",
        modeOfPayment: "Bank Transfer",
        type: "credit",
        amount: 99000,
    },
    {
        transactionId: "TXN-2024-016",
        customerName: "Sanjay",
        date: "29 MAY,2024",
        category: "Diamond",
        modeOfPayment: "UPI",
        type: "debit",
        amount: 57000,
    },
    {
        transactionId: "TXN-2024-017",
        customerName: "Anjali",
        date: "22 APR,2024",
        category: "Kitty",
        modeOfPayment: "Scanner",
        type: "credit",
        amount: 73000,
    },
    {
        transactionId: "TXN-2024-018",
        customerName: "Deepak",
        date: "16 MAR,2024",
        category: "Gold investors",
        modeOfPayment: "Bank Transfer",
        type: "debit",
        amount: 34000,
    },
    {
        transactionId: "TXN-2024-019",
        customerName: "Kavita",
        date: "11 FEB,2024",
        category: "E-Commerce",
        modeOfPayment: "UPI",
        type: "credit",
        amount: 88000,
    },
    {
        transactionId: "TXN-2024-020",
        customerName: "Tarun",
        date: "05 JAN,2024",
        category: "Diamond",
        modeOfPayment: "Scanner",
        type: "debit",
        amount: 46000,
    }
]